import type { SVGProps } from "react";

export const OlympicGamesIcon = (props: SVGProps<SVGSVGElement>) => {
  return (
    <svg height="16" width="16" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg" fill="none" {...props}>
      <circle
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="square"
        strokeMiterlimit="10"
        cx="10"
        cy="21"
        r="7"
        strokeLinejoin="miter"
      />
      <circle
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="square"
        strokeMiterlimit="10"
        cx="24"
        cy="21"
        r="7"
        strokeLinejoin="miter"
      />
      <circle
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="square"
        strokeMiterlimit="10"
        cx="17"
        cy="28"
        r="7"
        strokeLinejoin="miter"
      />
      <circle
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="square"
        strokeMiterlimit="10"
        cx="31"
        cy="28"
        r="7"
        strokeLinejoin="miter"
      />
      <circle
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="square"
        strokeMiterlimit="10"
        cx="38"
        cy="21"
        r="7"
        strokeLinejoin="miter"
      />
    </svg>
  );
};
