import type { SVGProps } from "react";

export const ConnectedDots3Icon = (props: SVGProps<SVGSVGElement>) => {
  return (
    <svg height="16" width="16" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill="none" {...props}>
      <line
        data-cap="butt"
        data-color="color-2"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeMiterlimit="10"
        x1="7.6"
        y1="10.5"
        x2="16.4"
        y2="5.5"
        strokeLinejoin="miter"
        strokeLinecap="butt"
      />
      <line
        data-cap="butt"
        data-color="color-2"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeMiterlimit="10"
        x1="7.6"
        y1="13.5"
        x2="16.4"
        y2="18.5"
        strokeLinejoin="miter"
        strokeLinecap="butt"
      />
      <circle
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="square"
        strokeMiterlimit="10"
        cx="5"
        cy="12"
        r="3"
        strokeLinejoin="miter"
      />
      <circle
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="square"
        strokeMiterlimit="10"
        cx="19"
        cy="4"
        r="3"
        strokeLinejoin="miter"
      />
      <circle
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="square"
        strokeMiterlimit="10"
        cx="19"
        cy="20"
        r="3"
        strokeLinejoin="miter"
      />
    </svg>
  );
};
